# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Hypso1
                                 A QGIS plugin
 This is a plugin for data analysis for HYPSO-1
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-05
        copyright            : (C) 2022 by Edmond Baloku
        email                : edmondbv@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Hypso1 class from file Hypso1.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hypso_1 import Hypso1
    return Hypso1(iface)
